# Generated by Django 4.0.1 on 2022-03-15 10:37

from django.db import migrations, models
import django.db.models.expressions


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Fornecedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(db_index=True, error_messages={'unique': 'Cultura já cadastrada.'}, max_length=200, unique=True)),
                ('ativo', models.BooleanField(default=False)),
            ],
            options={
                'ordering': [django.db.models.expressions.OrderBy(django.db.models.expressions.F('nome'))],
            },
        ),
    ]
